# Generated by Django 2.2.4 on 2021-09-08 12:03

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=24, null=True)),
                ('is_phone_number_verify', models.BooleanField(default=False)),
                ('is_education_agent', models.BooleanField(default=False)),
                ('is_migration_agent', models.BooleanField(default=False)),
                ('is_accountant_agent', models.BooleanField(default=False)),
                ('is_natti_translator_agent', models.BooleanField(default=False)),
                ('is_end_user', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=64)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=32)),
                ('profile_picture', models.FileField(upload_to='profile_pictures/')),
                ('headline', models.CharField(max_length=72)),
                ('description', models.CharField(max_length=600)),
                ('offer_online', models.BooleanField(default=False)),
                ('offer_offline', models.BooleanField(default=False)),
                ('client_city', models.CharField(max_length=32)),
                ('client_state', models.CharField(max_length=32)),
                ('client_zip_code', models.CharField(max_length=16)),
                ('client_country', models.CharField(max_length=32)),
                ('languages', models.TextField()),
                ('education_agent', models.BooleanField(default=False)),
                ('queac_number', models.CharField(blank=True, max_length=32, null=True)),
                ('education_agent_certificate', models.FileField(blank=True, null=True, upload_to='education_agent_certificates/')),
                ('education_agent_experience', models.IntegerField(default=0)),
                ('marn_number', models.CharField(blank=True, max_length=32, null=True)),
                ('migration_agent_certificate', models.FileField(blank=True, null=True, upload_to='migration_agent_certificates/')),
                ('migration_agent_experience', models.IntegerField(default=0)),
                ('naati_certificate', models.FileField(blank=True, null=True, upload_to='naati_certificates/')),
                ('naati_experience', models.IntegerField(default=0)),
                ('account_agent_experience', models.IntegerField(default=0)),
                ('australian_nation_id', models.FileField(upload_to='australian_nation_id/')),
                ('utility_bill', models.FileField(upload_to='utility_bill/')),
                ('status', models.CharField(choices=[('approve', 'approve'), ('suspend', 'suspend'), ('reactivate', 'reactivate'), ('pending', 'pending')], default='pending', max_length=16)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
