# Generated by Django 2.2.4 on 2021-09-19 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210919_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='australian_nation_id',
            field=models.FileField(default='', upload_to='australian_nation_id/'),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='city',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='client_city',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='client_country',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='client_state',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='client_zip_code',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='country',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='description',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='education_agent_certificate',
            field=models.FileField(default='', upload_to='education_agent_certificates/'),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='first_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='headline',
            field=models.CharField(default='', max_length=72, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='languages',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='last_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='marn_number',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='migration_agent_certificate',
            field=models.FileField(default='', upload_to='migration_agent_certificates/'),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='naati_certificate',
            field=models.FileField(default='', upload_to='naati_certificates/'),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='nationality',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='profile_picture',
            field=models.FileField(default='', upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='queac_number',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='state',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='street_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='utility_bill',
            field=models.FileField(default='', upload_to='utility_bill/'),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='zip_code',
            field=models.CharField(default='', max_length=16),
        ),
    ]
