# Generated by Django 2.2.4 on 2021-09-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210919_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalinformation',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
