# Generated by Django 2.2.4 on 2021-09-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userpersonalinformation_is_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalinformation',
            name='client_street_address',
            field=models.TextField(default=''),
        ),
    ]
