# Generated by Django 2.2.4 on 2021-10-02 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userpersonalinformation_client_street_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpersonalinformation',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userpersonalinformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
