# Generated by Django 2.2.4 on 2021-10-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='order',
            field=models.TextField(default='{}'),
        ),
    ]
