# Generated by Django 2.2.4 on 2021-09-10 14:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_clientorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientOrder',
            new_name='Order',
        ),
    ]
