# Generated by Django 2.2.4 on 2021-09-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210910_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='agent_id',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='client',
        ),
    ]
