# Generated by Django 2.2.4 on 2021-09-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_agentbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentbalance',
            name='available_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='agentbalance',
            name='pending_amount',
            field=models.FloatField(default=0),
        ),
    ]
