# Generated by Django 2.2.4 on 2021-09-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210921_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='status',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0),
        ),
    ]
