# Generated by Django 2.2.4 on 2021-09-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210921_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentservices',
            name='category',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='agentservices',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='agentservices',
            name='photo',
            field=models.FileField(default=0, upload_to='service_mages/'),
        ),
        migrations.AlterField(
            model_name='agentservices',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agentservices',
            name='sub_category',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='agentservices',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
