# Generated by Django 2.2.4 on 2021-10-08 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_auto_20211002_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservicereview',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
