# Generated by Django 2.2.4 on 2021-10-11 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatroom_order'),
        ('home', '0013_clientservicereview_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chats.ChatGroup')),
            ],
        ),
    ]
